CREATE TABLE IF NOT EXISTS "AUTHORITY" (
  "authority_id" BIGSERIAL PRIMARY KEY,
  "role" VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "STATUS" (
  "status_id" BIGSERIAL PRIMARY KEY,
  "status_name" VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "EVENT_TYPE" (
  "event_id" BIGSERIAL PRIMARY KEY,
  "event_name" VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "DB_SESSION" (
  "sid" VARCHAR NOT NULL PRIMARY KEY,
  "sess" JSON NOT NULL,
  "expire" TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS "IDX_DB_SESSION_EXPIRE" ON "DB_SESSION" ("expire");
